### ISSUE TITLE
ModuleNotFoundError: No module named 'connections'

### ISSUE THREAD

**Issue by ctr26** [IDR/idr-py#22]
Hi all,
I'm have difficulties connecting to the IDR at all with python.

```
conda env create -f environment.yml -n idr-omero
conda activate idr-omero
```

I followed these instructions with python3.6 and ran 

```
import omero
import idr
```

and get

`ModuleNotFoundError: No module named 'connections'`

So I tried the docker file from: https://github.com/IDR/idr-notebooks (python 2.7), which does get me further connecting but for:

```
import idr
import omero
from idr import connection
conn = connection()
```

'''
ClientError: No host specified. Use omero.client(HOSTNAME), ICE_CONFIG, or similar.
'''
So now I'm a bit stuck because I've run out of ideas. Any help would be great.
-------
Edit:
After some further playing:

`conn = connection("https://idr.openmicroscopy.org/api")`
returns 
`ClientError: No username specified`

Does this mean the public aren't supposed to be interacting with the IDR programmatically?

Best

Craig

**Comment by manics** [comment]
Hi

We're in the process of releasing a new version. The current release on bioconda has conflicts with some other dependencies so we're using our own channel for now. If you're happy to use Python 3 the following will install our dev version:
```
conda create -n idr-test -c ome -c idr idr-py
conda activate idr-test
```
You can then connect using:
```python
from idr import connection
conn = connection('idr.openmicroscopy.org', 'public', 'public')
```

```

**Comment by ctr26** [comment]
I'm trying to connect to the IDR but Python ends up being busy at 

from idr import connection
conn = connection('idr.openmicroscopy.org', 'public', 'public'),

the same happens when I try the same on Java. Is the IDR ok?

**Comment by joshmoore** [comment]
Thanks for the heads up, @ctr26. I can now reproduce via `idr.connection` even though a direct login is working. We're looking into it.

**Comment by joshmoore** [comment]
@ctr26: the IDR API should now be accessible again. If you have any issues, please feel free to open a new issue. Thanks again!

**Comment by ctr26** [comment]
Hi Josh,That's fixed it, what was the issue

**Comment by joshmoore** [comment]
With our data center currently being migrated (https://twitter.com/IDRstatus/status/1238097397114458118), we're on reduced capacity. The server you had been assigned needed to be restarted. Do let us know if you have any other issues and keep your 🤞 for a speedy migration!
